server:
  contextPath : /first
  port: 8080
  session:
      cookie:
        name: OAUTH2SESSION # This is to prevent cookie clash with other service as they run on the same host and context path

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9763/oauth2/token
      userAuthorizationUri: http://localhost:9763/oauth2/authorize
      clientId: Cc9o0iXH405CJdSEaG3VqcfAWksa
      clientSecret: OQ4KheiWrJXJIdP_t0UkbFwMzsoa
      scope: openid
      preEstablishedRedirectUri: http://localhost:8080/first/login
      clientAuthenticationScheme: header
      useCurrentUri: false

    resource:
      userInfoUri: http://localhost:9763/oauth2/userinfo?schema=openid
wso2SessionTerminateUrl: http://localhost:9763/commonauth?commonAuthLogout=true&type=oid&commonAuthCallerPath=http://localhost:8080/first/logout&relyingParty=localhost


spring:
  resources:
    chain:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG